version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Simulasi deploy
          command: |
            echo "Mulai deploy..."
            # Simulasi: Gagal dengan exit 1
            ./deploy.sh || echo "failed" > deploy_status.txt

      - run:
          name: Set deploy status
          command: |
            if [ -f deploy_status.txt ]; then
              echo 'export DEPLOY_STATUS=failed' >> $BASH_ENV
            else
              echo 'export DEPLOY_STATUS=success' >> $BASH_ENV
            fi

  log_to_spreadsheet:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install gspread oauth2client
      - run:
          name: Tulis log ke Google Spreadsheet
          command: |
            python logToSpreadsheet.py

workflows:
  version: 2
  deploy_and_log:
    jobs:
      - deploy
      - log_to_spreadsheet:
          requires:
            - deploy
          filters:
            branches:
              only: main
          # Always jalan, walau deploy gagal
          # CircleCI classic: pakai "when: always"
          # Kalau pakai CircleCI >2.1, udah default behavior asalkan pakai `requires`
