version: 2.1

jobs:
  log-deployment:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install gspread oauth2client
      - run:
          name: Log to Google Sheets
          command: |
            export DEPLOY_STATUS="SUCCESS"
            export DEPLOY_MESSAGE="Deployed without issue"
            python logToSpreadsheet.py

workflows:
  version: 2
  deploy_and_log:
    jobs:
      - log-deployment
