version: 2.1

jobs:
  log-deployment:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run logging script
          command: python webDepLogging.py
          command: python apiDepLogging.py

workflows:
  logging-deployment-data:
    jobs:
      - log-deployment
