version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Simulasi Deploy (bisa gagal)
          command: |
            node index.js || echo "DEPLOY_STATUS=failed" > deploy-status.txt

      - run:
          name: Simpan Status Deploy
          command: |
            if [ -f deploy-status.txt ]; then
              DEPLOY_STATUS=$(cat deploy-status.txt | grep DEPLOY_STATUS | cut -d '=' -f2)
            else
              DEPLOY_STATUS="success"
            fi
            echo "export DEPLOY_STATUS=$DEPLOY_STATUS" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install Python & pip Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install gspread oauth2client requests

      - run:
          name: Logging ke Google Sheet
          command: python3 logToSpreadsheet.py
          command: python3 logToSpreadsheet2.py
          when: always

workflows:
  version: 2
  deploy_and_log:
    jobs:
      - deploy
