version: 2.1

jobs:
  log-deployment:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run logging script
          command: python logToSpreadsheet12.py

workflows:
  scheduled-logging:
    triggers:
      - schedule:
          # Cron format: minute hour day month day-of-week
          # "0 1 * * *" = setiap hari jam 01:00 UTC (08:00 WIB)
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master   # workflow jalan hanya di branch master
    jobs:
      - log-deployment
