version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10

jobs:
  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Simulasi deploy (bisa gagal)
          command: |
            echo "Mulai deploy"
            # Simulasi kegagalan (ubah ke `true` kalau mau sukses)
            false
      - run:
          name: Set status deploy ke file
          when: always
          command: |
            if [ $? -eq 0 ]; then
              echo "success" > deploy_status.txt
            else
              echo "failed" > deploy_status.txt
            fi
      - persist_to_workspace:
          root: .
          paths:
            - deploy_status.txt

  log_to_spreadsheet:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install deps
          command: pip install gspread oauth2client
      - run:
          name: Log ke Google Spreadsheet
          command: |
            export DEPLOY_STATUS=$(cat deploy_status.txt)
            python logToSpreadsheet.py

workflows:
  version: 2
  deploy_and_log:
    jobs:
      - deploy
      - log_to_spreadsheet:
          requires:
            - deploy